### ISSUE TITLE
getCodeList() breaks for the METOA code list

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-prod/icesVocab#15]
The getCodeList function breaks when I try and use it on the METOA code list e.g. 

```
temp <- getCodeList('METOA')
```

I think this is because the long description for the code "CNA" has a carriage return in it which causes the XML string to get split in two.  The following code added to the start of the parseVocab() function fixes the issue for me (but it does make assumptions that the XML can just be stuck back together):

```
parseVocab <- function(xml) {
  
  # check if xml has been incorrectly broken up e.g. by a misplaced carriage return
  if (length(xml)>1){
    xml <- paste(xml,collapse="")
  }
...

```

**Comment by cekv** [comment]
@colinpmillar - this has not been removed. This is unfortunately how we get data from SeaDataNets EDMO list - so any local changes gets nullified when Vocab does 1:1 upload with the SeaDataNet server. David found 37 instances of carriage returns in the EDMO list.

**Comment by rix133** [comment]
The same error is also with the **Harbour_LOCODE** list

**Comment by colinpmillar** [comment]
thank you all, I will be working on this this afternoon, thanks for all the comments

**Comment by davidcurrie2001** [comment]
> The same error is also with the **Harbour_LOCODE** list

@rix133 The following works fine for me:
```
library(icesVocab)
myList <- getCodeList('Harbour_LOCODE')
```
v1.1.9 of icesVocab and R v4.0.2 (64 bit).

**Comment by rix133** [comment]
> > The same error is also with the **Harbour_LOCODE** list
> 
> @rix133 The following works fine for me:
> 
> ```
> library(icesVocab)
> myList <- getCodeList('Harbour_LOCODE')
> ```
> 
> v1.1.9 of icesVocab and R v4.0.2 (64 bit).

I get an error with the latest github version (sessininfo attached). Rest of the codes (except METOA and EDMO) work fine.

```
library(icesVocab)
myList <- getCodeList('Harbour_LOCODE')
```
**Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  Opening and ending tag mismatch: a1 line 1 and Description [76]**

 `sessionInfo()`
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Estonian_Estonia.1257  LC_CTYPE=Estonian_Estonia.1257   
[3] LC_MONETARY=Estonian_Estonia.1257 LC_NUMERIC=C                     
[5] LC_TIME=Estonian_Estonia.1257    
system code page: 1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] icesVocab_1.1.9

loaded via a namespace (and not attached):
[1] compiler_4.0.5 xml2_1.3.2

**Comment by colinpmillar** [comment]
Hi all,
I am running R-4.1.1 and the recent github version and dont get any errors. Can you try and repoduce the error?

```r
library(icesVocab)
myList <- getCodeList("Harbour_LOCODE")
sessionInfo()
```

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)  
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C
[5] LC_TIME=English_United Kingdom.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] icesVocab_1.1.9

loaded via a namespace (and not attached):
[1] compiler_4.1.1 xml2_1.3.2
```

**Comment by rix133** [comment]
This is somehow related to locale, by chaining this to e.g US the code works also on R version 4.0.5
```
library(icesVocab)

Sys.setlocale("LC_ALL","English")

myList <- getCodeList("Harbour_LOCODE")

sessionInfo()
```

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] icesVocab_1.1.9

loaded via a namespace (and not attached):
[1] compiler_4.0.5 xml2_1.3.2  `
```

**Comment by colinpmillar** [comment]
thanks @rix133 this was definately the issue, and it stems from the fact that we have used `download.file` to download the text from the webservice, saving it as a text file, and then reading from it as UTF-8.  It seems that download.file will always save the file in the local encoding and canot be forced to use UTF-8. And it also seems that some of the characters in the code lists that are causing problems cannot be converted from estonian back to utf-8.

I have a fix which is to read directly from the url and bypass writing the file to disc before reading.  I think we did this to improve speed, but it seems to be at the cost of opening up the possibility of side effects due to different local encodings.

**Comment by colinpmillar** [comment]
So the consequence of reading direct from the url is speed. But I think it is nessisary for now. So I will push these changes and then update CRAN early next week.

**Comment by colinpmillar** [comment]
Would one of you mind checking this and then I can close?
Thanks!

**Comment by rix133** [comment]
@colinpmillar  Yes, work for locale: Estonian You are right the time to get the codes is significantly increased :)

**Comment by colinpmillar** [comment]
Thank you @rix133 i'll close for now.

**Comment by davidcurrie2001** [comment]
The following also works for me now - thanks @colinpmillar 
```
library(devtools)
install_github("ices-tools-prod/icesVocab")
library(icesVocab)
temp <- getCodeList('EDMO')
```
