### ISSUE TITLE
getCodeDetail() error

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-prod/icesVocab#16]
getCodeDetail() return an error when I try to use it with the ICES_StockCode. It works for certain stock_codes ("her.27.irls", "had-34")  but not for others ("pil.27.8c9a","ane.27.9a" ).

getCodeDetail("ICES_StockCode", "ane.27.9a")
The output from this function is developing.  please do not rely on the current output format
Error: `x` must be a string of length 1
In addition: Warning message:
In if (xml == "") { :
  the condition has length > 1 and only the first element will be used

**Comment by colinpmillar** [comment]
Hi @lucalamoni I think the most recent updates to the package (#17) fix this issue. If you can check they work for you after installing the most recent version that would be great.

**Comment by lucalamoni** [comment]
Thank you Colin, it seems to work well now!
